### ISSUE TITLE
Unable to get confirmation code when setting up the integration

### ISSUE THREAD

**Issue by GZ-3** [rospogrigio/airbnk_mqtt#31]
Hello everyone! 
I have this issue that I can't set up the home assistnant integration. When I put my email in the integration and press submit it just keeps loading and doesn't send me a verification code or anything. It stays that way for hours. Are their servers not working anymore?

**Comment by rospogrigio** [comment]
I frankly don't know... Does it work if you try to login on the app?

**Comment by GZ-3** [comment]
It does log in when I use my email in the app. It seems the integration has a problem with my email @yandex, I switched to gmail and it works just fine!
Thank You very much for this awesome work you've done!
