### ISSUE TITLE
Signal strength sensor

### ISSUE THREAD

**Issue by formatBCE** [rospogrigio/airbnk_mqtt#4]
I wonder, maybe, that precision is overwhelming a bit for sensor.
Now it writes as soon as ESP is sending data. It floods state db pretty much (2-3 times per second).
Can we make some skips maybe, to have values each 3-5 seconds instead?

**Comment by rospogrigio** [comment]
Strange, I get advert data every 1-2 seconds, are you really getting 2-3 times per second?
Anyway, I'll try to make the sensor update less frequent, give me some days.
How about your custom firmware?
Bye
