### ISSUE TITLE
Integration does not create cover entities, only sensor entities

### ISSUE THREAD

**Issue by ezfrag2021** [rospogrigio/airbnk_mqtt#43]
Lock: WeHere M532
ESP32: ESP32-D0WD-V3 v3.0
Firmware: Tasmota 13.4.1.2 (117cee9-bluetooth)

MQTT is working fine and the sensor entities are being reported (locked/unlocked appears to be reversed). However, no cover entity was created by the integration 
![Screenshot 2024-05-01 at 11 38 13](https://github.com/rospogrigio/airbnk_mqtt/assets/93487625/709cf7ab-deb5-4d5e-9b84-943782908d85)

**Comment by ezfrag2021** [comment]
@formatBCE Just shouting you out since you seem to be the most active of the developers in this space and I wondered if you could make any suggestions?

**Comment by ezfrag2021** [comment]
@formatBCE No worries. Thanks for the response. Did you find a better smart lock? I've been searching forever for a fast zigbee device and settled on this one hoping it would one day get supported by Z2MQTT in HA.

**Comment by formatBCE** [comment]
> @formatBCE No worries. Thanks for the response. Did you find a better smart lock? I've been searching forever for a fast zigbee device and settled on this one hoping it would one day get supported by Z2MQTT in HA.

I moved to my own place, so had more freedom in picking the lock. Unfortunately, there's almost no locks with Zigbee... I bought keyless Yale with Z-wave. Just wanted to be completely local, without cloud accounts of any kind. My Airbnk was great for tenancy, but it was time to say good bye :)

**Comment by ezfrag2021** [comment]
Update - I decided to dig into the integration to see what I could understand and noticed that there were two airbnk integrations within the custom components directory. I uninstalled the integration in Home Assistant, deleted both the custom component folders and then reinstalled the integration via HACS and everything is working as expected now.
